#关系型数据库配置
[mysql]
host = "127.0.0.1"
port = 3306
database = "dousheng"
username = "root"
password = "root"
charset = "utf8mb4"
parse_time = true
loc = "Local"


#nosql配置
[redis]
host = "127.0.0.1"
port = 6379
database = 0

#记录当前服务器的ip和启动端口号，当前服务器的ip用于生成对应的视频链接地址
[server]
ip = "127.0.0.1"
port = 8087