#关系型数据库配置
[mysql]
host = "127.0.0.1"
port = 3306
database = "dousheng2"
username = "root"
password = "123456"
charset = "utf8"
parse_time = true
loc = "Local"

#nosql配置
[redis]
host = "127.0.0.1"
port = 6379
database = 0

#记录当前服务器的ip和启动端口号，当前服务器的ip用于生成对应的视频链接地址
[server]
ip = "10.101.130.35"
port = 8087